databases:
  - name: bd
    plan: free
    databaseName: bd_09sa
    user: bd_09sa_user

services:
  - type: web
    plan: free
    name: bd
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python manage.py runserver'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4