# Generated by Django 5.1.7 on 2025-04-17 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('presence', models.IntegerField(default=1)),
                ('vigor', models.IntegerField(default=1)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='character.character')),
            ],
        ),
    ]
