# Generated by Django 5.1.7 on 2025-04-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrobaticts', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('animal_handling', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('arts', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('athletics', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('current_affairs', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('science', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('crime', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('diplomacy', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('deception', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('fortitude', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('stealth', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('initiative', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('intimidation', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('insight', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('investigation', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('fight', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('medicine', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('ocultism', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('perception', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('piloting', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('aim', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('profession', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('reflexes', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('religion', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('survival', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('tatics', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('technology', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('will', models.JSONField(blank=True, default={'bonus': 0, 'level': 'U', 'total': 0})),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='character.character')),
            ],
        ),
    ]
