# Generated by Django 5.1.7 on 2025-04-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='character.character'),
        ),
    ]
