# Generated by Django 5.1.7 on 2025-05-24 15:57

import apps.character.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_skill_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='acrobaticts',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='aim',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='animal_handling',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='arts',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='athletics',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='crime',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='current_affairs',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='deception',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='diplomacy',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='fight',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='fortitude',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='initiative',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='insight',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='intimidation',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='investigation',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='medicine',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ocultism',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='perception',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='piloting',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profession',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='reflexes',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='religion',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='science',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stealth',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='survival',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tatics',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='technology',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
        migrations.AlterField(
            model_name='skill',
            name='will',
            field=models.JSONField(blank=True, default=apps.character.models.get_default_skill),
        ),
    ]
