# Generated by Django 5.1.7 on 2025-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_skill_acrobaticts_alter_skill_aim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
