# Generated by Django 5.1.7 on 2025-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='skills',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
