# Generated by Django 5.1.7 on 2025-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hp_per_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='initial_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='initial_pe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='initial_sanity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='pe_per_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='profociency',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='sanity_per_level',
            field=models.IntegerField(default=0),
        ),
    ]
