# Generated by Django 5.1.7 on 2025-06-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_class_hp_per_level_class_initial_hp_class_initial_pe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='character.class')),
            ],
        ),
    ]
