# Generated by Django 5.1.7 on 2025-07-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
    ]
