# Generated by Django 5.1.7 on 2025-07-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_remove_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
