# Generated by Django 5.1.7 on 2025-07-22 18:56

import apps.character.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_character_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=apps.character.models.get_default_inventory, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
