# Generated by Django 5.1.7 on 2025-07-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.class'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.origin'),
        ),
        migrations.AddField(
            model_name='character',
            name='subclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.subclass'),
        ),
        migrations.CreateModel(
            name='AvailableAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.JSONField(blank=True, default=dict, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableParanormalPowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powers', models.JSONField(blank=True, default=dict, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableRituals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rituals', models.JSONField(blank=True, default=dict, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
