# Generated by Django 5.1.7 on 2025-09-11 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0015_character_clas_character_level_character_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progression', models.JSONField(blank=True, default=dict, null=True)),
                ('class_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to='character.class')),
            ],
        ),
    ]
