# Generated by Django 5.1.7 on 2025-04-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('execution', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('buff', models.IntegerField()),
                ('buff_type', models.CharField(max_length=100)),
                ('pe_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rituals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ritual_type', models.CharField(max_length=100)),
                ('ritual_level', models.IntegerField()),
                ('description', models.TextField()),
                ('execution', models.CharField(blank=True, max_length=100, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('pe_cost', models.IntegerField()),
                ('occultism_dt', models.IntegerField()),
                ('sanity_cost', models.IntegerField()),
                ('buff', models.IntegerField(blank=True, null=True)),
                ('buff_type', models.CharField(blank=True, max_length=100, null=True)),
                ('damage_dice', models.IntegerField(blank=True, null=True)),
                ('damage_multiplier', models.IntegerField(blank=True, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resistence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('student_description', models.TextField(blank=True, null=True)),
                ('student_execution', models.CharField(blank=True, max_length=100, null=True)),
                ('student_range', models.CharField(blank=True, max_length=100, null=True)),
                ('student_target', models.CharField(blank=True, max_length=100, null=True)),
                ('student_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('student_pe_cost', models.IntegerField(blank=True, null=True)),
                ('student_ritual_type', models.CharField(blank=True, max_length=100, null=True)),
                ('student_buff', models.IntegerField(blank=True, null=True)),
                ('student_buff_type', models.CharField(blank=True, max_length=100, null=True)),
                ('student_damage_dice', models.IntegerField(blank=True, null=True)),
                ('student_damage_multiplier', models.IntegerField(blank=True, null=True)),
                ('student_damage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('student_resistence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('student_sanity_cost', models.IntegerField(blank=True, null=True)),
                ('student_occultism_dt', models.IntegerField(blank=True, null=True)),
                ('true_description', models.TextField(blank=True, null=True)),
                ('true_execution', models.CharField(blank=True, max_length=100, null=True)),
                ('true_range', models.CharField(blank=True, max_length=100, null=True)),
                ('true_target', models.CharField(blank=True, max_length=100, null=True)),
                ('true_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('true_pe_cost', models.IntegerField(blank=True, null=True)),
                ('true_ritual_type', models.CharField(blank=True, max_length=100, null=True)),
                ('true_buff', models.IntegerField(blank=True, null=True)),
                ('true_buff_type', models.CharField(blank=True, max_length=100, null=True)),
                ('true_damage_dice', models.IntegerField(blank=True, null=True)),
                ('true_damage_multiplier', models.IntegerField(blank=True, null=True)),
                ('true_damage_type', models.CharField(max_length=100)),
                ('true_resistence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('true_sanity_cost', models.IntegerField(blank=True, null=True)),
                ('true_occultism_dt', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
