# Generated by Django 5.1.7 on 2025-04-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rituals',
            name='true_damage_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
