# Generated by Django 5.1.7 on 2025-04-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_alter_rituals_true_damage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rituals',
            name='student_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rituals',
            name='true_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
