# Generated by Django 5.1.7 on 2025-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0003_rituals_student_level_rituals_true_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='rituals',
            name='affinity',
            field=models.BooleanField(default=False),
        ),
    ]
