# Generated by Django 5.1.7 on 2025-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0004_rituals_affinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rituals',
            name='student_affinity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rituals',
            name='true_affinity',
            field=models.BooleanField(default=False),
        ),
    ]
