# Generated by Django 5.1.7 on 2025-05-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0005_rituals_student_affinity_rituals_true_affinity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rituals',
            name='occultism_dt',
        ),
        migrations.RemoveField(
            model_name='rituals',
            name='sanity_cost',
        ),
        migrations.RemoveField(
            model_name='rituals',
            name='student_occultism_dt',
        ),
        migrations.RemoveField(
            model_name='rituals',
            name='student_ritual_type',
        ),
        migrations.RemoveField(
            model_name='rituals',
            name='student_sanity_cost',
        ),
        migrations.RemoveField(
            model_name='rituals',
            name='true_occultism_dt',
        ),
        migrations.RemoveField(
            model_name='rituals',
            name='true_ritual_type',
        ),
        migrations.RemoveField(
            model_name='rituals',
            name='true_sanity_cost',
        ),
    ]
