# Generated by Django 5.1.7 on 2025-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0006_remove_rituals_occultism_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='buff',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='buff_type',
        ),
        migrations.AddField(
            model_name='ability',
            name='passive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ability',
            name='resistence_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
