# Generated by Django 5.1.7 on 2025-06-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0007_remove_ability_buff_remove_ability_buff_type_and_more'),
        ('character', '0009_subclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability', to='character.class'),
        ),
        migrations.AddField(
            model_name='ability',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ability',
            name='origin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability', to='character.origin'),
        ),
    ]
