# Generated by Django 5.1.7 on 2025-06-03 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0008_ability_clas_ability_level_ability_origin'),
        ('character', '0009_subclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='subclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability', to='character.subclass'),
        ),
    ]
