# Generated by Django 5.1.7 on 2025-06-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0009_ability_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
