# Generated by Django 5.1.7 on 2025-06-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0010_alter_ability_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='execution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='pe_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
