# Generated by Django 5.1.7 on 2025-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0011_alter_ability_duration_alter_ability_execution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
