# Generated by Django 5.1.7 on 2025-06-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0012_alter_ability_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='attribute_requirement',
            field=models.CharField(blank=True, choices=[('strength', 'str'), ('dexterity', 'dex'), ('intelligence', 'int'), ('presence', 'pre'), ('vigor', 'vig')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='attribute_requirement_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='skill_requirement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='skill_requirement_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
