# Generated by Django 5.1.7 on 2025-06-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0013_ability_attribute_requirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='skill_requirement_value',
        ),
        migrations.AddField(
            model_name='ability',
            name='skill_requirement_level',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
