# Generated by Django 5.1.7 on 2025-06-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0014_remove_ability_skill_requirement_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='abilit_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability_requirement', to='abilities.ability'),
        ),
    ]
