# Generated by Django 5.1.7 on 2025-06-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0015_ability_abilit_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParanormalPowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('power_type', models.CharField(max_length=100)),
                ('passive', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('attribute_requirement', models.CharField(blank=True, choices=[('strength', 'str'), ('dexterity', 'dex'), ('intelligence', 'int'), ('presence', 'pre'), ('vigor', 'vig')], max_length=100, null=True)),
                ('attribute_requirement_value', models.IntegerField(blank=True, null=True)),
                ('skill_requirement', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_requirement_level', models.CharField(blank=True, max_length=1, null=True)),
                ('execution', models.CharField(blank=True, max_length=100, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('pe_cost', models.IntegerField()),
                ('buff', models.IntegerField(blank=True, null=True)),
                ('buff_type', models.CharField(blank=True, max_length=100, null=True)),
                ('damage_dice', models.IntegerField(blank=True, null=True)),
                ('damage_multiplier', models.IntegerField(blank=True, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resistence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('affinity_description', models.TextField(blank=True, null=True)),
                ('affinity_buff', models.IntegerField(blank=True, null=True)),
                ('affinity_buff_type', models.CharField(blank=True, max_length=100, null=True)),
                ('affinity_damage_dice', models.IntegerField(blank=True, null=True)),
                ('affinity_damage_multiplier', models.IntegerField(blank=True, null=True)),
                ('affinity_damage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('affinity_resistence_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
