# Generated by Django 5.1.7 on 2025-06-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0016_paranormalpowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paranormalpowers',
            name='pe_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
