# Generated by Django 5.1.7 on 2025-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0017_alter_paranormalpowers_pe_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='paranormalpowers',
            name='number_of_pre_powers',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='paranormalpowers',
            name='number_of_pre_powers_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
