# Generated by Django 5.1.4 on 2024-12-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=50)),
                ('weapon_proficiency', models.CharField(choices=[('SW', 'Simple Weapon'), ('TW', 'Tatical Weapon'), ('HW', 'Heavy Weapon')], default='SW', max_length=50)),
                ('weapon_type', models.CharField(choices=[('ML', 'Melee - Light'), ('MOH', 'Melee - One Hand'), ('MTH', 'Melee - Two Hands'), ('SWTH', 'Shooting Weapon - Two Hands'), ('FWL', 'Fire Weapons - Light'), ('FWTH', 'Fire Weapons - Two Hands'), ('RTH', 'Ranged - Two Hands')], default='ML', max_length=50)),
                ('weapon_category', models.IntegerField()),
                ('weapon_damage_dice_quantity', models.IntegerField()),
                ('weapon_damage_dice', models.IntegerField()),
                ('weapon_threat_range', models.IntegerField(default=0)),
                ('weapon_critical_multiplier', models.IntegerField(default=2)),
                ('weapon_range', models.CharField(choices=[('ML', 'Melee'), ('S', 'Short'), ('M', 'Medium'), ('L', 'Long')], default='ML', max_length=50)),
                ('weapon_spaces', models.IntegerField(default=0)),
            ],
        ),
    ]
