# Generated by Django 5.1.4 on 2024-12-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weapon_damage_type',
            field=models.CharField(choices=[('I', 'Impact'), ('S', 'Sharp'), ('P', 'Piercing'), ('B', 'Ballistic'), ('F', 'Fire')], default='I', max_length=50),
        ),
    ]
