# Generated by Django 5.1.4 on 2024-12-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_weapon_weapon_ammo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_ammo',
            field=models.CharField(choices=[('SB', 'Short Bullets'), ('LB', 'Long Bullets'), ('SS', 'Shotgun Shells'), ('F', 'Fuel'), ('A', 'Arrow'), ('R', 'Rocket')], default='SB', max_length=50),
        ),
    ]
