# Generated by Django 5.1.7 on 2025-03-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_weapon_weapon_ammo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeponMods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_types', models.CharField(choices=[('MS', 'Melee and Shooting'), ('FW', 'Fire Weapons'), ('AM', 'AMMO')], default='MS', max_length=2)),
                ('modification', models.CharField(max_length=100)),
                ('effect', models.CharField(max_length=100)),
                ('buff_type', models.CharField(choices=[('ATK', 'Attack'), ('DMG', 'Damage'), ('CTRC', 'Critical Chance'), ('CTRM', 'Critical Multiplier'), ('OTH', 'Other')], default='ATK', max_length=4)),
                ('buff_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(choices=[('ML', 'Melee - Light'), ('MOH', 'Melee - One Hand'), ('MTH', 'Melee - Two Hands'), ('SWTH', 'Shooting Weapon - Two Hands'), ('FWL', 'Fire Weapons - Light'), ('FWOH', 'Fire Weapons - One Hand'), ('FWTH', 'Fire Weapons - Two Hands'), ('RTH', 'Ranged - Two Hands')], default='ML', max_length=50),
        ),
    ]
