# Generated by Django 5.1.7 on 2025-04-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_weponmods_alter_weapon_weapon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammo', models.CharField(choices=[('N', '---'), ('SB', 'Short Bullets'), ('LB', 'Long Bullets'), ('SS', 'Shotgun Shells'), ('F', 'Fuel'), ('A', 'Arrow'), ('R', 'Rocket')], default='N', max_length=50)),
                ('pack_quantity', models.IntegerField()),
                ('pack_cenes', models.IntegerField()),
                ('spaces', models.IntegerField()),
            ],
        ),
    ]
