# Generated by Django 5.1.7 on 2025-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_ammo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammo',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
