# Generated by Django 5.1.7 on 2025-04-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_ammo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='ammo_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
