# Generated by Django 5.1.7 on 2025-04-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_weapon_ammo_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_type', models.CharField(choices=[('L', 'Light'), ('S', 'Shild'), ('H', 'Heavy')], default='L', max_length=50)),
                ('category', models.IntegerField()),
                ('ac_bonus', models.IntegerField()),
                ('spaces', models.IntegerField()),
            ],
        ),
    ]
