# Generated by Django 5.1.7 on 2025-04-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_armor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.CharField(max_length=50)),
                ('effect', models.TextField()),
                ('bonus', models.IntegerField()),
                ('spaces_bonus', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='weponmods',
            name='effect',
            field=models.TextField(),
        ),
    ]
