# Generated by Django 5.1.7 on 2025-04-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_armormod_alter_weponmods_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=50)),
                ('equipment_category', models.IntegerField()),
                ('equipment_description', models.TextField()),
                ('equipment_type', models.CharField(max_length=50)),
                ('spaces', models.IntegerField()),
            ],
        ),
    ]
