# Generated by Django 5.1.7 on 2025-04-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_generalequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalequipment',
            name='equipment_category',
            field=models.IntegerField(choices=[('A', 'Accessories'), ('E', 'Explosives'), ('OPI', 'Operetional Items')]),
        ),
    ]
