# Generated by Django 5.1.7 on 2025-04-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_alter_generalequipment_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalequipment',
            name='equipment_category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generalequipment',
            name='equipment_type',
            field=models.CharField(choices=[('A', 'Accessories'), ('E', 'Explosives'), ('OPI', 'Operetional Items')], default='A', max_length=50),
        ),
    ]
