# Generated by Django 5.1.7 on 2025-04-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0015_alter_generalequipment_equipment_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificattion', models.CharField(max_length=50)),
                ('effect', models.TextField()),
                ('bonus', models.IntegerField()),
                ('spaces_bonus', models.IntegerField()),
            ],
        ),
    ]
