# Generated by Django 5.1.7 on 2025-04-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0016_accessoriesmod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParanormalItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.IntegerField()),
                ('description', models.TextField()),
                ('spaces', models.IntegerField()),
            ],
        ),
    ]
