# Generated by Django 5.1.7 on 2025-09-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_paranormalitens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeponMods',
            new_name='WeaponMods',
        ),
    ]
